# Generated by Django 5.2.14 on 2026-05-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("alt_text", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
