# Generated by Django 5.2.14 on 2026-05-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0002_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
