# Generated by Django 5.2.14 on 2026-05-12 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0003_category_display_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="homepage/banners/")),
                ("redirect_url", models.URLField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="Enabled", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryMainGrid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_grid",
                        to="dash.category",
                    ),
                ),
                (
                    "editor_choice_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editor_choice_1",
                        to="dash.article",
                    ),
                ),
                (
                    "editor_choice_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editor_choice_2",
                        to="dash.article",
                    ),
                ),
                (
                    "editor_choice_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editor_choice_3",
                        to="dash.article",
                    ),
                ),
                (
                    "editor_choice_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="editor_choice_4",
                        to="dash.article",
                    ),
                ),
                (
                    "featured_article",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_main_article",
                        to="dash.article",
                    ),
                ),
            ],
        ),
    ]
