# Generated by Django 5.2.14 on 2026-05-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0004_homepagebanner_categorymaingrid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
