# Generated by Django 5.2.14 on 2026-05-15 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0005_alter_category_display_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="BylineLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Work Email Address"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional.",
                        max_length=15,
                        verbose_name="Phone Number",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "organisation",
                    models.CharField(
                        help_text='Company, institution, or "Independent" if freelancing.',
                        max_length=200,
                        verbose_name="Organisation / Company",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        max_length=200, verbose_name="Designation / Title"
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("op_ed", "Guest Op-Ed (Free)"),
                            ("columnist", "Resident Columnist (Pro)"),
                            ("brand", "Brand Collab (Enterprise)"),
                        ],
                        default="op_ed",
                        help_text="Which Byline program are you applying for?",
                        max_length=20,
                        verbose_name="Program Tier",
                    ),
                ),
                (
                    "topic_idea",
                    models.TextField(
                        help_text="What do you want to write about? Give us a topic, an angle, and why our readers need to read it. Even a few sentences is enough to start.",
                        verbose_name="Article / Content Idea",
                    ),
                ),
                (
                    "writing_sample",
                    models.URLField(
                        blank=True,
                        help_text="Link to a published article, LinkedIn post, or any writing sample. Optional but helpful.",
                        verbose_name="Writing Sample URL",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, verbose_name="LinkedIn Profile URL"),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="Website / Portfolio URL"),
                ),
                (
                    "brand_name",
                    models.CharField(
                        blank=True,
                        help_text="Only required for Brand Collab applicants.",
                        max_length=200,
                        verbose_name="Brand / Client Name",
                    ),
                ),
                (
                    "monthly_volume",
                    models.CharField(
                        blank=True,
                        help_text="Approximate number of articles per month — Brand Collab only.",
                        max_length=100,
                        verbose_name="Expected Monthly Article Volume",
                    ),
                ),
                (
                    "consent_publish",
                    models.BooleanField(
                        default=False,
                        help_text="I understand that published articles will carry my byline and may be shared across Corporate Impact's print, digital, and social channels.",
                        verbose_name="Consent to Publish",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("reviewing", "Reviewing"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Lead Status",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Editorial team use only — not visible to the applicant.",
                        verbose_name="Internal Notes",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        help_text="Name of the editor handling this lead.",
                        max_length=100,
                        verbose_name="Assigned Editor",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Submitted At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
            ],
            options={
                "verbose_name": "Byline Lead",
                "verbose_name_plural": "Byline Leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="dash_byline_status_884b8a_idx"
                    ),
                    models.Index(fields=["tier"], name="dash_byline_tier_1c461e_idx"),
                    models.Index(
                        fields=["created_at"], name="dash_byline_created_87ee2b_idx"
                    ),
                    models.Index(fields=["email"], name="dash_byline_email_817bfe_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HomemakerLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional — include country code e.g. +91 98765 43210",
                        max_length=15,
                        verbose_name="Phone Number",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "story_summary",
                    models.TextField(
                        help_text="Tell us about yourself — your journey, what you manage, and what makes your story worth telling.",
                        verbose_name="Your Story",
                    ),
                ),
                (
                    "years_as_homemaker",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Years as a Homemaker"
                    ),
                ),
                (
                    "is_entrepreneur",
                    models.BooleanField(
                        default=False,
                        help_text="Tick if you run any kind of business, home enterprise, or side venture.",
                        verbose_name="Running a Business or Side Venture?",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if not applicable.",
                        max_length=200,
                        verbose_name="Business / Venture Name",
                    ),
                ),
                (
                    "instagram_handle",
                    models.CharField(
                        blank=True,
                        help_text="@handle — optional but helpful for amplification.",
                        max_length=100,
                        verbose_name="Instagram Handle",
                    ),
                ),
                (
                    "spotlight_type",
                    models.CharField(
                        choices=[
                            ("story", "Share My Story"),
                            ("interview", "Request an Interview"),
                            ("otm", "Homemaker of the Month"),
                            ("write", "Write for the Column"),
                        ],
                        default="story",
                        max_length=20,
                        verbose_name="How Would You Like to Be Featured?",
                    ),
                ),
                (
                    "consent_publish",
                    models.BooleanField(
                        default=False,
                        help_text="I agree that Corporate Impact may publish my story across print, digital, and social media.",
                        verbose_name="Consent to Publish",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("reviewing", "Reviewing"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Lead Status",
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Editorial team use only — not visible to the applicant.",
                        verbose_name="Internal Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Submitted At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
            ],
            options={
                "verbose_name": "Homemaker Lead",
                "verbose_name_plural": "Homemaker Leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="dash_homema_status_ac2d3d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="dash_homema_created_a3e3fd_idx"
                    ),
                    models.Index(
                        fields=["spotlight_type"], name="dash_homema_spotlig_46baca_idx"
                    ),
                ],
            },
        ),
    ]
