# Generated by Django 5.2.14 on 2026-05-15 05:28

import dash.leads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0006_bylinelead_homemakerlead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bylinelead",
            name="writing_sample",
            field=models.FileField(
                blank=True,
                help_text="Upload a PDF sample (Max 5MB).",
                null=True,
                upload_to="writing_samples/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    dash.leads.validate_file_size,
                ],
                verbose_name="Writing Sample (PDF)",
            ),
        ),
    ]
