# Generated by Django 5.2.14 on 2026-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0007_alter_bylinelead_writing_sample"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageAds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="homepage_ads/")),
                ("redirect_url", models.URLField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("Enabled", "Enabled"), ("Disabled", "Disabled")],
                        default="Enabled",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
