# Generated by Django 5.2.14 on 2026-06-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dash", "0008_homepageads"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("youtube_url", models.URLField(max_length=500)),
                ("youtube_video_id", models.CharField(blank=True, max_length=20)),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="featured_videos/"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Enabled", "Enabled"), ("Disabled", "Disabled")],
                        default="Enabled",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
