# Generated by Django 6.1.1 on 2026-09-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_featuredvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_nav',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(blank=True, default='Enabled', max_length=100, null=True),
        ),
    ]
