# Generated by Django 6.1.1 on 2026-09-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_category_show_in_nav_team_display_order_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
