# Generated by Django 6.1.1 on 2026-09-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_gallery_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=1500, unique=True),
        ),
    ]
