# Generated by Django 6.1.1 on 2026-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(blank=True, max_length=1500, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, max_length=1500, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=1500, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='slug',
            field=models.CharField(blank=True, max_length=1500, unique=True),
        ),
    ]
